### ISSUE TITLE
Required attr. support for inputs

### ISSUE THREAD

**Issue by lansolo99** [creativetimofficial/material-tailwind#165]
Hi, 

One of the thing I always need is the required attribute for fields. In MUI, addind a "required" prop also appends an asterisk after the label.

I struggled a bit to be able to append it myself as "required" is not a prop here and I couldn't pass element for the label. The "after" pseudo element is already taken for the focus animation, so the only workaround I found was to use the before element and play with TW classes such as : 

```JSX

 <Input
variant='standard'
label='Téléphone portable'
labelProps={{
   className: "required-input-field-label peer-placeholder-shown:text-base before:content-['*'] before:text-red-500 peer-placeholder-shown:before:left-[148px] before:absolute before:left-[102px] peer-focus:before:left-[102px]"
}}
className='text-base text-grey-800'
/>
```

```CSS
.required-input-field-label {
    &:before {
      transition-property: left;
      transition-timing-function: ease-out;
      transition-duration: 150ms;
    }
  }
```
As you can see, it's pretty ugly because the TW JIT dynamic values only match with the current label length.
I think it would be nice to be able to either pass a custom element as label or to support the required attr. and auto add the usual asterisk element. Or just tell me if you have already figured out a way to solve this problem..

Otherwise, happy to get rid of the original cumbersome MUI lib 👍
