### ISSUE TITLE
Inputs not working properly while using html package

### ISSUE THREAD

**Issue by its-dev-fer** [creativetimofficial/material-tailwind#233]
Hi, I am using angular with tailwind configured, added withMT in my tailwind.config.js and inputs are not working as expected, let me give you some examples:

> I have this form
<img width="376" alt="image" src="https://user-images.githubusercontent.com/27165409/192792608-a8f33bb9-6f51-48ed-a93a-7c937f932419.png">

> Everything seems to work fine but when you type something:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/27165409/192792885-428f8efb-9474-4ad3-8b3c-4ebc3b6bc26e.png">

Neither the switch button seems to be working when you click it

I could give you my configurations let me know if I messed up in something:

```javascript

// taiwlind.config.js

/** @type {import('tailwindcss').Config} */
const withMT = require("@material-tailwind/html/utils/withMT");

module.exports = withMT(
  {
    content: ["./src/**/*.{html,js}"],
    theme: {
      extend: {
        zIndex:{
          "-1": "-1"
        },
        transformOrigin: {
          "0": "0%",
        },
      },
    },
    variants: { borderColor: ["responsive", "hover", "focus", "focus-within"] },
    plugins: [],
  }
)
```

```scss

/* Angular's global styles.scss */

@tailwind base;
@tailwind components;
@tailwind utilities;

input:focus-within ~ label,
input:not(:placeholder-shown) ~ label {
  @apply transform scale-75 -translate-y-6;
}

input:focus-within ~ label {
  @apply text-blue-500;
}

.outline input:focus-within ~ label,
.outline input:not(:placeholder-shown) ~ label {
  @apply transform scale-75 -translate-y-4 z-0 ml-3 px-1 py-0;
}
```

Package.json as well

```JSON
{
  "name": "la-tiendita-del-mamado",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host=0.0.0.0",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "build_css": "postcss src/styles.scss -o src/tailwind.css"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.0.0",
    "@angular/common": "^14.0.0",
    "@angular/compiler": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/forms": "^14.0.0",
    "@angular/platform-browser": "^14.0.0",
    "@angular/platform-browser-dynamic": "^14.0.0",
    "@angular/router": "^14.0.0",
    "@angular/service-worker": "^14.0.0",
    "@material-tailwind/html": "^1.2.1",
    "choices.js": "^10.1.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.0.0",
    "@angular/cli": "~14.0.0",
    "@angular/compiler-cli": "^14.0.0",
    "@types/jasmine": "~4.0.0",
    "autoprefixer": "^10.4.12",
    "jasmine-core": "~4.1.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "postcss-cli": "^10.0.0",
    "tailwindcss": "^3.1.8",
    "typescript": "~4.7.2"
  }
}

```
