### ISSUE TITLE
Cannot read property Font family of undefined when using material tailwind with vite

### ISSUE THREAD

**Issue by ioofy** [creativetimofficial/material-tailwind#260]
Hello i just  got error when adding configuration about material tailwind into my project

![image](https://user-images.githubusercontent.com/77242429/205832223-279feb53-3a3a-4429-9ba2-7410853f3190.png)

my config tailwind
```js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withMT = require("@material-tailwind/react/utils/withMT");

module.exports = withMT({
  content: ["./*.html", "./src/**/*.{js,jsx,ts,tsx}"],
  plugins: [],
});

```

postcss
```js
module.exports = {
  modules: true,
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
```

App.tsx
```tsx
import React from "react";
import { createRoot } from "react-dom/client";
import { ThemeProvider } from "@material-tailwind/react";
// tailwind styles
import "styles/index.css";
import App from "./App";

type RootElement = Element | DocumentFragment;

const rootElement = document.getElementById("root");
const renderRoot = createRoot(rootElement as RootElement);

renderRoot.render(
  <React.Fragment>
    <ThemeProvider>
      <App />
    </ThemeProvider>
  </React.Fragment>,
);
```

styles
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  html {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
  }
}
```

am i wrong with this config?
