### ISSUE TITLE
Change background color with text color when TabHeader item was active

### ISSUE THREAD

**Issue by TREER00T** [creativetimofficial/material-tailwind#279]
According to tailwind's [docs](https://www.material-tailwind.com/docs/react/tabs) I used tabs but when I started implementing without changing the code I ran into problems.

The problem is related to changing the background rank and text color of the active item in the Tab header section. First, I tried to write a role for this tag using css, with this I was only able to change the color of the active item, but I could not change the color of the text of the active item.

The css code I wrote

```css
li[role:tab] div.absulate {
  background-color: #2675EC
}

li[role:tab] div.z-20 {
  color: white
}
```

Do you think there is a solution to fix it?
